### ISSUE TITLE
Employee Personal Data Clarification

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/contracts#3]
Clause 21.2.

> The Employee consents to the Company making such information available to those who provide products or services to the Company (such as advisers and payroll administrators) regulatory authorities and potential purchasers of the Company or any part of its business in which the Employee works, and as may be required by law.

Proposal to add the following:
`The Company will only make the minimum personal information required by external parties.`

The reasoning is that this aligns with our ethos and manifesto.

**Comment by iteles** [comment]
DEFINITELY. I would work this into the main sentence rather than adding it to the end - people will remember the first impression!

(and I think you're missing the word `available` from that sentence) 😉 

See [manifesto.md](https://github.com/dwyl/start-here/blob/master/manifesto.md):
> Your data is yours.
