### ISSUE TITLE
Employee Handbook

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/contracts#7]
Create Employee Handbook

public nature of dwyl - anything has potential to become public
Booking holiday
Sick leave
grievance procedures - approach verbally, report in writing
20% time
zappos quitting bonus?

**Comment by iteles** [comment]
Will this also cover freelancers? If so, can we call it something that reflects that?

'New Joiner' handbook? 'dwyler' handbook?

**Comment by markwilliamfirth** [comment]
This one's just for employees - It will mostly include stuff like sick leave, holiday, etc

We can also create a handbook for contractors if required - what guidelines did you want to include for contractors? Shall we open another issue?

**Comment by nelsonic** [comment]
@markwilliamfirth could we have a "Full Timers" Section in the "DWYLers Handbook" that is _specific_ to people who have decided `commit` to being "full time". 😉

**Comment by iteles** [comment]
It would actually be nice to have everything for all dwylers in the same handbook and you just look at the section that's most relevant to you (but get to see everything). Thoughts @markwilliamfirth ?

**Comment by markwilliamfirth** [comment]
moved to hq
